language: node_js
node_js:
  - "0.12"
  - "0.11"
  - "0.10"
  - "iojs"
  - "iojs-v1.0.4"

notifications:
  email:
    - lilyfpace@gmail.com

deploy:
  provider: heroku
  api_key: "15adb709-7273-4d90-9513-5b5f9ee5a9db"
