language: node_js
node_js:
- '0.12'
- '0.11'
- '0.10'
- iojs
- iojs-v1.0.4
before_install:
- npm install -g grunt-cli
- npm install -g mustache
- npm install -g grunt
- npm install -g mocha
- npm install
- npm update
- git clone git://github.com/n1k0/casperjs.git ~/casperjs
- cd ~/casperjs
- git checkout tags/1.0.2
- export PATH=$PATH:`pwd`/bin
- cd -

env:
  global:
    - APP_NAME=trello-bug-counter
before_script:
- npm run mocha-test
- phantomjs --version
- casperjs --version
- git push -f git@heroku.com:$APP_NAME.git master
- yes
notifications:
  email:
    recipients:
      - lily@generalui.com
deploy:
  provider: heroku
  api_key:
    secure: q6tc0IMlKFtJAuKipRwHb/xSqbCOIsgUcJPKyumQgXrT5jrrgP89vvJA3Nv6pcs38aZpRs87E68QDPs3XS3h7lKy7cszs8Vx550H6hW5TNAnsNPehHh+NkaZSikfJ05Nq0/Q2ZvdP7l5IDSi/sFiSX6mlimQbcvRSxV8xlbfEY9gJhqHLCrfK3ILWSmfZJ2T98mf5ZD9+I181+K6umzwO7rysylX1WrSOC+ShohgRzrYno3wDcalJiep+E5I5Yj0QtSue25yjqt5CMC75TAOgsickBDA1hP8b1Cbq+rsjolyFMqXSsrNoudDaugoa4MP/kJBivbqMtkybpR7LnWWdg==
  app: trello-bug-counter
