language: node_js
node_js:
- '0.12'
- '0.11'
- '0.10'
- iojs
- iojs-v1.0.4
before_install:
- npm install -g grunt-cli
- npm install -g mustache
- npm install -g grunt
- npm install -g mocha
- npm install
- npm update
- git clone git://github.com/n1k0/casperjs.git ~/casperjs
- cd ~/casperjs
- git checkout tags/1.0.2
- export PATH=$PATH:`pwd`/bin
- cd -
- which heroku || wget -qO- https://toolbelt.heroku.com/install-ubuntu.sh | sh

env:
  global:
    - APP_NAME=trello-bug-counter
    - secure: eeIr1caawFrhMwBXuof7VeZYDnjhACfoIZUKjXUn/SiQg9peTZvdrz9VSwtzJ2iX2NMKGoT968QOk9atSnzRXOoCLLlR833d3nfUBeg3pS71WqeiJ/4IxB72f3FdqGGh65LBDSJN3qIKiFN85WvD4Piw9vUhTq64RAppVRPadamdE36jqtMdYKvgnXF6jAbkIvPqqfh2rdMeOXYoEgQ3JoTSO3CWEnvz4lZ3x5hhVsZw1A4i6+ePD9yj4vPgAMudpDngDfnCaiRq2UTuzHED1A0r32KwOX2FIOskI3E/4tn93G5ccYuAZEtJIV0OgJ2B6yL5mA0GVH4ecIFBkL4brA==

before_script:
- npm run mocha-test
- phantomjs --version
- casperjs --version
- git remote -v | grep ^heroku || heroku git:remote --ssh-git --app $APP_NAME
- git push -f git@heroku.com:$APP_NAME.git master

notifications:
  email:
    recipients:
      - lily@generalui.com
deploy:
  provider: heroku
  api_key:
    secure: THtq5USX3f3r6obppqmVTTQ4whAZh0tLdGhj5VTvDS4OYfLZsYbd7U1ErMcpbNS90OAqILPNWQpPQpx9L3MQ3yhsYKRdupJedJDZiTMTNnzWwIqB2doR8wJ+duOfUPHdaXDtgi29TNDjydMVe0T70PJ95DcuNp+9g0n3AFkgIEk=
  app: trello-bug-counter
