language: node_js
node_js:
- '0.12'
- '0.11'
- '0.10'
- iojs
- iojs-v1.0.4
notifications:
  email:
    recipients:
    - lilyfpace@gmail.com
  irc: irc.freenode.org##thejavascripts
deploy:
  provider: heroku
  api_key:
    secure: OoUlijdVHfqXuzbic384T0eZdXv5JREbZDB/ueG5VrL9pL5KbxCIY7rZcTfemt3kwcQkBsBmT+5KJPT6exdmu6nkpKdr+VtPCPNf59nCIEdG1SaVPggQmtP97ggqfzH2j7GqJxMO8PcoDzaaF2pCXo6wQlH3skN2TZEzgAd20eU=
  app: trello-bug-counter
  on:
    repo: lilyfromseattle/trello-bugs
